//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnevnikTroskova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potkategorija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Potkategorija()
        {
            this.Unos = new HashSet<Unos>();
        }
    
        public int IdPotkategorije { get; set; }
        public int IdKategorije { get; set; }
        public string Naziv { get; set; }
        public int Pozicija { get; set; }
    
        public virtual Kategorija Kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unos> Unos { get; set; }
    }
}
