//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnevnikTroskova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unos
    {
        public int IdUnosa { get; set; }
        public int IdPotkategorije { get; set; }
        public double Iznos { get; set; }
        public string Opis { get; set; }
        public string Vrsta { get; set; }
        public System.DateTime DatumVrijeme { get; set; }
    
        public virtual Potkategorija Potkategorija { get; set; }
    }
}
